# Generated by Django 2.2.6 on 2019-11-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hNum', models.IntegerField()),
                ('thresh', models.IntegerField()),
                ('currLoad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hostel'),
        ),
    ]
