# Generated by Django 2.2.6 on 2019-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191105_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hName',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
