# Generated by Django 2.2.7 on 2019-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_hostel_hname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
